[package]
name = "rustbridge-cli"
version = "0.1.0"
authors = ["technetos <mrgould93@gmail.com>"]

[dependencies]
quicli = "0.2.0"
failure = "0.1.1"
failure_derive = "0.1.1"
diesel = { version = "1.0.0", features = ["postgres"] }
data-encoding = "2.1.1"
ring = "0.12.1"
